---
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: validating-webhook
webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6VENDQXJXZ0F3SUJBZ0lVTmcyVDJIL3NSbU5BeUpvNGsrbk43ZGRnc0tjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERWVNQndHQTFVRUF3d1ZkbUZzYVdSaGRHVXVkbUZzCmFXUmhkR1V1YzNaak1CNFhEVEkxTURRek1EQTVORGd6TTFvWERUSTRNREl4T0RBNU5EZ3pNMW93WlRFTE1Ba0cKQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTUdFbHVkR1Z5Ym1WMApJRmRwWkdkcGRITWdVSFI1SUV4MFpERWVNQndHQTFVRUF3d1ZkbUZzYVdSaGRHVXVkbUZzYVdSaGRHVXVjM1pqCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdW8vays3MlZ6amVHWGF5TGwzNmoKU2tUa24xT3p2Z2tINEtYZDhCM1dLNElsdnhqWUZWZ3laY2lsL0xGbUFXdTRvcnlMTmkyK1N0MEt1U0RZWUozYwpLUEY5VVJCRVVkOFZaeHo5Nlp0cFBlMlk3b05IRjlXRFZXZlVySDZOL3JhNG03c1RwVm5zQkU1SGM5ZVZ0QWZJCmNjZHB3cXlGVmhBdmtZeU95Q09pVnlKV2hQcGVCUEw3RC9MQjE4OVo4aXR4aGNmaGp2K1RjV1VVaWR1T2dyb3IKV0IvYXM0MnVjakVuRnJ3d0piV1NEbnFMaWR2RXhZNStuRkpDUzNOOXZxdjhKekRkSWYvSFU0SVNHdk9zY0VScgpZNndzNjF2eUJpSlB1UVB0cG5JaUhsencxZ1RRYVoxRVZzWXM2MUJjMUdyaUhYUko2MnJOR29jZHoyOEJ1ZXRICjl3SURBUUFCbzNVd2N6QWRCZ05WSFE0RUZnUVVDRHpjSk5jNS9xSUJqUVZ2OFRHWEtKbDdOWDh3SHdZRFZSMGoKQkJnd0ZvQVVDRHpjSk5jNS9xSUJqUVZ2OFRHWEtKbDdOWDh3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFnQmdOVgpIUkVFR1RBWGdoVjJZV3hwWkdGMFpTNTJZV3hwWkdGMFpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCkFEcldlYXZuNXlDaWZhb29RM0lDREtQNUNaTFVOUUNqdVp4YUVFai9oWktVZzIxRDMwRVJhZDQ5WFJZUzJ4REEKd1JZVmUzeU9LbUJaZENaZW9HOWFORFhUVkNCUlpBVDYrT3hXVEdIVTVwdmk5N2lqaDRPbk0wMTJINGJSZ2hVbQorVksyTVhScWZrd0liZEplT1Y1RVN0Uk4xRkNUdVJDOUVJaXJRR0NXV0ZoU2F4dE03NkEyZUl1eGM4Z3dCSVhuCmJNbUhDWVRsSkFaVGxrVUltd05TK3RnT1hiLzg3aHBQZytTSVdlZFMvQnRzdnZNVm9haW13TzNNWFJwUTdVTjIKa084cVB5RmN3WUlCZEluL0pVYThxSWdFZmg0eFU1TTlxL2hXM29xTzRjRDlhdEZXY1AyR3BPSWRnL1NJRkVlYwpmdDF2TU8vUEFnZlBidkxjSnRXc2tJZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: validate
        name: validate
        path: /validate/pods
    failurePolicy: Fail
    name: validate.validate.svc
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 15